/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formlar;

import Baglanti.VeritabaniBaglanti;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author UsErim
 */
public class Kullanici extends javax.swing.JFrame {

    Kayit ky = new Kayit();
    int kisino = 0;
    
    public Kullanici() {
        initComponents();
    }
    public Kullanici(String kadi,String sifre) throws SQLException{
        initComponents();
        VeritabaniBaglanti vb = new VeritabaniBaglanti();
        vb.baglan();
        
        //Kişi Bilgileri Sorgularının olduğu bölüm
        String sorgu = "SELECT * FROM kullanicilar WHERE kadi = " +"\"" + kadi +"\" and sifre = " + "\"" + sifre +"\"";
        vb.stmt = vb.con.createStatement();
        ResultSet rs = vb.stmt.executeQuery(sorgu);
        
        
        while(rs.next()){
        adTf.setText(rs.getString("ad"));
        soyadTf.setText(rs.getString("soyad"));
        tcTf.setText(rs.getString("tcno"));
        sicilTf.setText(rs.getString("sicilno"));
        cinsiyetCbx.setSelectedItem(rs.getString("cinsiyet"));
        sehirCbx.setSelectedItem(rs.getString("sehir"));
        kadiTf.setText(rs.getString("kadi"));
        birimTf.setText(rs.getString("birim"));
        sifreTf.setText(rs.getString("sifre"));
        kayitNoLb.setText(String.valueOf(rs.getInt("kayitno")));
        dogumTf.setText(String.valueOf(rs.getDate("dogumtarihi")));
        kisino = rs.getInt("kayitno");
        }
        
        //Kişi İzin Bilgileri Olduğu Bölüm
        String sorgu2 = "SELECT * FROM izinler WHERE kisino = " + "\"" + kisino + "\"";
        rs = vb.stmt.executeQuery(sorgu2);
        while(rs.next()){
            kalanIzınLb.setText(String.valueOf(rs.getInt("kalanizin")));
            izinBasLb.setText(String.valueOf(rs.getDate("izinbaslangic")));
            izinBitLb.setText(String.valueOf(rs.getDate("izinbitis")));
            izinKulLb.setText(String.valueOf(rs.getInt("izinkullanilan")));
            izinTurLb.setText(rs.getString("izintur"));
        }
        
        vb.con.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        adTf = new javax.swing.JTextField();
        soyadTf = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        sicilTf = new javax.swing.JTextField();
        tcTf = new javax.swing.JTextField();
        cinsiyetCbx = new javax.swing.JComboBox<>();
        dogumTf = new javax.swing.JTextField();
        sehirCbx = new javax.swing.JComboBox<>();
        kadiTf = new javax.swing.JTextField();
        birimTf = new javax.swing.JTextField();
        kayitNoLb = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        kalanIzınLb = new javax.swing.JLabel();
        izinBasLb = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        izinBitLb = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        izinTurLb = new javax.swing.JLabel();
        izinKulLb = new javax.swing.JLabel();
        sifreTf = new javax.swing.JTextField();
        kaydet = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tumGoster = new javax.swing.JButton();
        yeniIzin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kullanıcı Ekranı");
        setBounds(new java.awt.Rectangle(0, 0, 430, 500));
        setPreferredSize(new java.awt.Dimension(430, 500));

        jLabel1.setText("Ad");

        jLabel2.setText("Soyad");

        jLabel3.setText("Tc No");

        jLabel4.setText("Sicil No");

        jLabel5.setText("Cinsiyet");

        jLabel6.setText("Doğum Tarihi");

        jLabel7.setText("Şehir");

        jLabel8.setText("Kullanıcı Adı");

        jLabel9.setText("Birim");

        jLabel10.setText("KayıtNo");

        jLabel16.setText("Şifre");

        tcTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcTfActionPerformed(evt);
            }
        });

        cinsiyetCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Erkek", "Kadın" }));

        sehirCbx.setModel(ky.sehirlerCombobox);

        kayitNoLb.setText("0");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("İzinler"));
        jPanel1.setToolTipText("");

        jLabel14.setText("İzin Türü");

        jLabel15.setText("Kullanılan İzin Miktarı");

        kalanIzınLb.setText("0");

        izinBasLb.setText("0");

        jLabel11.setText("Kalan İzin");

        jLabel12.setText("İzin Başlangıç Tarihi");

        izinBitLb.setText("0");

        jLabel13.setText("İzin Bitiş Tarihi");

        izinTurLb.setText("0");

        izinKulLb.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(izinKulLb))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(izinBasLb))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(kalanIzınLb))
                            .addComponent(izinBitLb, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(izinTurLb, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kalanIzınLb, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(izinBasLb)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(izinBitLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(izinTurLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(izinKulLb)))
        );

        kaydet.setText("Kullanıcı Bilgilerini Güncelle");
        kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydetActionPerformed(evt);
            }
        });

        jButton2.setText("Kaydetmeden Çık");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tumGoster.setText("Tüm İzinleri Göster");
        tumGoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tumGosterActionPerformed(evt);
            }
        });

        yeniIzin.setText("Yeni İzin");
        yeniIzin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yeniIzinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(kaydet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tumGoster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(yeniIzin, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(soyadTf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tcTf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sicilTf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cinsiyetCbx, javax.swing.GroupLayout.Alignment.LEADING, 0, 80, Short.MAX_VALUE)
                            .addComponent(dogumTf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adTf))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kadiTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sifreTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kayitNoLb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(birimTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sehirCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(adTf))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(soyadTf)
                            .addComponent(jLabel10)
                            .addComponent(kayitNoLb, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tcTf)
                            .addComponent(jLabel16)
                            .addComponent(sifreTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(sicilTf)
                            .addComponent(jLabel8)
                            .addComponent(kadiTf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cinsiyetCbx)
                            .addComponent(jLabel7)
                            .addComponent(sehirCbx))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(dogumTf)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(birimTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kaydet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tumGoster)
                    .addComponent(yeniIzin))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tcTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcTfActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tcTfActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tumGosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tumGosterActionPerformed
        new TumIzinler(kisino).setVisible(true);
    }//GEN-LAST:event_tumGosterActionPerformed

    private void yeniIzinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yeniIzinActionPerformed
        new YeniIzin(kisino).setVisible(true);
    }//GEN-LAST:event_yeniIzinActionPerformed

    private void kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydetActionPerformed
        VeritabaniBaglanti vb = new VeritabaniBaglanti();
        vb.baglan();
        
        String guncelle = "UPDATE kullanicilar SET ad = \"" + adTf.getText() + "\", soyad = \"" +
             soyadTf.getText() + "\", tcno = \"" + tcTf.getText() + "\", sicilno = \"" + sicilTf.getText() + 
             "\", cinsiyet = \"" + cinsiyetCbx.getSelectedItem() + "\", dogumtarihi = \"" +
             dogumTf.getText() + "\", sehir = \"" + sehirCbx.getSelectedItem() + "\", kadi = \"" +
             kadiTf.getText() + "\", birim = \"" + birimTf.getText() + "\", sifre = \"" +
             sifreTf.getText() +"\" WHERE kayitno = " + kisino + ";";
        
        try {
            vb.stmt = vb.con.createStatement();
            vb.stmt.executeUpdate(guncelle);
            vb.con.close();
            JOptionPane.showMessageDialog(rootPane, "Başarıyla Güncellendi");
        } catch (SQLException ex) {
            Logger.getLogger(Kullanici.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_kaydetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kullanici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kullanici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kullanici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kullanici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kullanici().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adTf;
    private javax.swing.JTextField birimTf;
    private javax.swing.JComboBox<String> cinsiyetCbx;
    private javax.swing.JTextField dogumTf;
    private javax.swing.JLabel izinBasLb;
    private javax.swing.JLabel izinBitLb;
    private javax.swing.JLabel izinKulLb;
    private javax.swing.JLabel izinTurLb;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kadiTf;
    private javax.swing.JLabel kalanIzınLb;
    private javax.swing.JButton kaydet;
    private javax.swing.JLabel kayitNoLb;
    private javax.swing.JComboBox<String> sehirCbx;
    private javax.swing.JTextField sicilTf;
    private javax.swing.JTextField sifreTf;
    private javax.swing.JTextField soyadTf;
    private javax.swing.JTextField tcTf;
    private javax.swing.JButton tumGoster;
    private javax.swing.JButton yeniIzin;
    // End of variables declaration//GEN-END:variables
}
