/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formlar;

import Baglanti.VeritabaniBaglanti;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author UsErim
 */
public class Yonetici extends javax.swing.JFrame {
    Kayit ky = new Kayit();
    VeritabaniBaglanti vb = new VeritabaniBaglanti();
    /**
     * Creates new form Yonetici
     */
    public Yonetici() {
        initComponents();
        
        vb.baglan();
        
        String sorgu = "SELECT * FROM kullanicilar WHERE kadi = \"root\" and sifre = \"root\"";
        try {
            vb.stmt = vb.con.createStatement();
            ResultSet rs = vb.stmt.executeQuery(sorgu);
            
            while(rs.next()){
                yoneticiKayitNoLb.setText(String.valueOf(rs.getInt("kayitno")));
                yoneticiadTf.setText(rs.getString("ad"));
                yoneticiSoyadTf.setText(rs.getString("soyad"));
                yoneticiTcTf.setText(rs.getString("tcno"));
                yoneticiSicilTf.setText(rs.getString("sicilno"));
                yoneticiCinsiyetCbx.setSelectedItem(rs.getString("cinsiyet"));
                yoneticiDogumTf.setText(String.valueOf(rs.getDate("dogumtarihi")));
                yoneticiSehirCbx.setSelectedItem(rs.getString("sehir"));
                yoneticiBirimTf.setText(rs.getString("birim"));
            }
            
            vb.con.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(Yonetici.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yoneticiKayitNoLb = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        yoneticiadTf = new javax.swing.JTextField();
        yoneticiSoyadTf = new javax.swing.JTextField();
        yoneticiGuncelle = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        yoneticiSicilTf = new javax.swing.JTextField();
        kBilListele = new javax.swing.JButton();
        yoneticiTcTf = new javax.swing.JTextField();
        yoneticiCinsiyetCbx = new javax.swing.JComboBox<>();
        yoneticiDogumTf = new javax.swing.JTextField();
        yoneticiSehirCbx = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        yoneticiBirimTf = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        araAdTf = new javax.swing.JTextField();
        araButon = new javax.swing.JButton();
        izinListButon = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        araSoyadTf = new javax.swing.JTextField();
        araSicilTf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Yönetici Ekranı");

        yoneticiKayitNoLb.setText("0");

        jLabel9.setText("Birim");

        jLabel10.setText("KayıtNo");

        yoneticiGuncelle.setText("Yönetici Bilgilerini Güncelle");
        yoneticiGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yoneticiGuncelleActionPerformed(evt);
            }
        });

        jLabel16.setText("Şifre");

        jButton2.setText("Kaydetmeden Çık");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        kBilListele.setText("Kullanıcı Bilgilerini Listele");
        kBilListele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kBilListeleActionPerformed(evt);
            }
        });

        yoneticiTcTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yoneticiTcTfActionPerformed(evt);
            }
        });

        yoneticiCinsiyetCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Erkek", "Kadın" }));

        yoneticiSehirCbx.setModel(ky.sehirlerCombobox);

        jLabel1.setText("Ad");

        jLabel2.setText("Soyad");

        jLabel3.setText("Tc No");

        jLabel4.setText("Sicil No");

        jLabel5.setText("Cinsiyet");

        jLabel6.setText("Doğum Tarihi");

        jLabel7.setText("Şehir");

        jLabel8.setText("Kullanıcı Adı");

        jLabel11.setText("root");

        jLabel12.setText("root");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Kullanıcı Arama"));

        jLabel13.setText("Ad");

        araButon.setText("Kullanıcıyı Ara");
        araButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                araButonActionPerformed(evt);
            }
        });

        izinListButon.setText("Kullanıcının Izinlerini Listele");
        izinListButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izinListButonActionPerformed(evt);
            }
        });

        jLabel14.setText("Soyad");

        jLabel15.setText("Sicil No");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(araAdTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(araSoyadTf)
                            .addComponent(araSicilTf, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(araButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(izinListButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(araAdTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(araButon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(izinListButon)
                    .addComponent(jLabel14)
                    .addComponent(araSoyadTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(araSicilTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(yoneticiSoyadTf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yoneticiTcTf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yoneticiSicilTf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yoneticiCinsiyetCbx, javax.swing.GroupLayout.Alignment.LEADING, 0, 80, Short.MAX_VALUE)
                            .addComponent(yoneticiDogumTf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yoneticiadTf))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(yoneticiKayitNoLb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(yoneticiBirimTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(yoneticiSehirCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(kBilListele, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(yoneticiGuncelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(yoneticiadTf))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(yoneticiSoyadTf)
                            .addComponent(jLabel10)
                            .addComponent(yoneticiKayitNoLb, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(yoneticiTcTf)
                            .addComponent(jLabel16)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(yoneticiSicilTf)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(yoneticiCinsiyetCbx)
                            .addComponent(jLabel7)
                            .addComponent(yoneticiSehirCbx))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(yoneticiDogumTf)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(yoneticiBirimTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yoneticiGuncelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kBilListele)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yoneticiGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yoneticiGuncelleActionPerformed

        
        
        String guncelle = "UPDATE kullanicilar SET ad = \"" + yoneticiadTf.getText() + "\", soyad = \"" +
             yoneticiSoyadTf.getText() + "\", tcno = \"" + yoneticiTcTf.getText() + "\", sicilno = \"" + yoneticiSicilTf.getText() + 
             "\", cinsiyet = \"" + yoneticiCinsiyetCbx.getSelectedItem() + "\", dogumtarihi = \"" +
             yoneticiDogumTf.getText() + "\", sehir = \"" + yoneticiSehirCbx.getSelectedItem() + "\", birim = \"" + yoneticiBirimTf.getText() + "\" WHERE kayitno = " + 1 + ";";
        
        try {
            vb.stmt = vb.con.createStatement();
            vb.stmt.executeUpdate(guncelle);
            vb.con.close();
            JOptionPane.showMessageDialog(rootPane, "Başarıyla Güncellendi");
        } catch (SQLException ex) {
            Logger.getLogger(Kullanici.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_yoneticiGuncelleActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void kBilListeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kBilListeleActionPerformed
        new KullaniciListele().setVisible(true);
    }//GEN-LAST:event_kBilListeleActionPerformed

    private void yoneticiTcTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yoneticiTcTfActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_yoneticiTcTfActionPerformed

    private void izinListButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izinListButonActionPerformed
        if(araAdTf.getText().equals("") || araSoyadTf.getText().equals("") || araSicilTf.getText().equals("")){
          JOptionPane.showMessageDialog(rootPane, "Lütfen Tüm Alanları Doldurun!", "Uyarı", JOptionPane.WARNING_MESSAGE);
      }else{
            vb.baglan();
            ResultSet rs;
            try {
                vb.stmt = vb.con.createStatement();
                rs = vb.stmt.executeQuery("SELECT * FROM kullanicilar WHERE ad = \""
                        + araAdTf.getText() + "\" and soyad = \""+ araSoyadTf.getText() 
                        + "\" and sicilno = \"" + araSicilTf.getText() +"\";");
            int kisino = 0;
            while(rs.next()){
                kisino  = rs.getInt("kayitno");
              } 
            vb.con.close();
            new TumIzinler(kisino).setVisible(true);
            
            } catch (SQLException ex) {
                Logger.getLogger(Yonetici.class.getName()).log(Level.SEVERE, null, ex);
            }
      }
    }//GEN-LAST:event_izinListButonActionPerformed

    private void araButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_araButonActionPerformed
      if(araAdTf.getText().equals("") || araSoyadTf.getText().equals("") || araSicilTf.getText().equals("")){
          JOptionPane.showMessageDialog(rootPane, "Lütfen Tüm Alanları Doldurun!", "Uyarı", JOptionPane.WARNING_MESSAGE);
      }else{
          new KullaniciListele(araAdTf.getText(), araSoyadTf.getText(), araSicilTf.getText()).setVisible(true);
          
      }
    }//GEN-LAST:event_araButonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Yonetici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Yonetici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Yonetici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Yonetici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Yonetici().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField araAdTf;
    private javax.swing.JButton araButon;
    private javax.swing.JTextField araSicilTf;
    private javax.swing.JTextField araSoyadTf;
    private javax.swing.JButton izinListButon;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kBilListele;
    private javax.swing.JTextField yoneticiBirimTf;
    private javax.swing.JComboBox<String> yoneticiCinsiyetCbx;
    private javax.swing.JTextField yoneticiDogumTf;
    private javax.swing.JButton yoneticiGuncelle;
    private javax.swing.JLabel yoneticiKayitNoLb;
    private javax.swing.JComboBox<String> yoneticiSehirCbx;
    private javax.swing.JTextField yoneticiSicilTf;
    private javax.swing.JTextField yoneticiSoyadTf;
    private javax.swing.JTextField yoneticiTcTf;
    private javax.swing.JTextField yoneticiadTf;
    // End of variables declaration//GEN-END:variables
}
